import swaggerJSDoc from "swagger-jsdoc";

// I keep Swagger configuration here so API documentation is separated from app setup.
export const swaggerSpec = swaggerJSDoc({
  definition: {
    openapi: "3.0.0",
    info: {
      title: "Generated Backend API",
      version: "1.0.0",
      description: "API documentation generated by Backend Forge",
    },
    servers: [
      {
        url: "http://localhost:5000/api/v1",
        description: "Local development server",
      },
    ],
  },
  apis: ["src/routes/*.ts", "src/modules/**/*.routes.ts"],
});