services:
  api:
    build: .
    container_name: backend-forge-api
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - redis
      - mongo

  mongo:
    image: mongo:7
    container_name: backend-forge-mongo
    ports:
      - "27017:27017"

  redis:
    image: redis:7
    container_name: backend-forge-redis
    ports:
      - "6379:6379"